[env:ATmega2560]
platform = atmelavr
board = megaatmega2560
framework = arduino
lib_deps =
	adafruit/Adafruit Unified Sensor@^1.1.15
	adafruit/Adafruit BMP280 Library@^3.0.0
	lordmax2/klevebrand-all-drone-controller-core@^3.0.0
	lordmax2/klevebrand-drone-gyro-bno085@^3.0.0
	adafruit/Adafruit BNO08x@^1.2.5
upload_speed = 115200
monitor_speed = 115200
monitor_filters = default
; Using latest here: https://github.com/ZakKemble/avr-gcc-build/releases/ to get nice c++ features
platform_packages = toolchain-atmelavr@${sysenv.PIO_AVR_GCC_PATH}
build_unflags = -std=gnu++11 -std=gnu++14 -std=gnu++17
build_flags = -std=gnu++20


